# syntax=docker/dockerfile:1.4

FROM sccache AS sccache

FROM solana AS anchor

COPY --from=sccache /usr/bin/sccache /usr/bin/sccache

WORKDIR /build

ARG RUST_STABLE_TOOLCHAIN="1.75.0"
ARG ANCHOR_VERSION="0.30.0"

ENV SHELL=/bin/bash
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH

RUN <<EOF
#!/usr/bin/env bash

set -eux

apt-get update -y
apt-get upgrade -y

# TODO: remove libsecp256k1-dev
apt-get install -y --no-install-recommends \
    curl gnupg ca-certificates jq pkg-config build-essential libudev-dev gcc-multilib git libsecp256k1-dev

echo "Install Node.js and Yarn"
curl -o- https://deb.nodesource.com/setup_lts.x | bash
curl -LSs https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" >/etc/apt/sources.list.d/yarn.list

apt-get update -y
apt-get install -y --no-install-recommends \
    nodejs \
    yarn

# add non-root user
groupadd -g 1000 nonroot
useradd -u 1000 -g 1000 -s /bin/bash -m nonroot

# install rustup, use minimum components
curl -L "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init" -o rustup-init
chmod +x rustup-init
./rustup-init -y --no-modify-path --profile minimal --default-toolchain ${RUST_STABLE_TOOLCHAIN}
rm rustup-init

chown -R root:nonroot ${RUSTUP_HOME} ${CARGO_HOME}
chmod -R g+w ${RUSTUP_HOME} ${CARGO_HOME}

rustup show

cargo install --git https://github.com/coral-xyz/anchor --tag v${ANCHOR_VERSION} anchor-cli --locked
/usr/bin/sdk/sbf/scripts/install.sh

sccache --version
cargo --version
rustc --version
anchor --version
node --version
npm --version
yarn --version

# cargo clean up
# removes compilation artifacts cargo install creates (>250M)
rm -rf "${CARGO_HOME}/registry" "${CARGO_HOME}/git" /root/.cache/sccache

# apt clean up
apt-get autoremove -y
apt-get clean
rm -rf /var/lib/apt/lists/*

EOF

# show backtraces
ENV RUST_BACKTRACE=1

WORKDIR /root/

ENTRYPOINT ["/bin/bash"]
