# syntax=docker/dockerfile:1.4

FROM node as builder

WORKDIR /workspace

RUN <<EOF
#!/usr/bin/env bash

set -eux

apt-get update -y
apt-get install -y --no-install-recommends \
    git

git clone --branch master https://github.com/ZeusNetworkHQ/zeusscan-ui-v0
cd zeusscan-ui-v0
git checkout 76a6ac507fd604b4560ca091312d1e8426b16f12

npm install
npm run css

EOF

FROM node-alpine as btc-rpc-explorer

WORKDIR /workspace

COPY --from=builder /workspace/zeusscan-ui-v0 .

EXPOSE 3002

ENTRYPOINT ["npm", "start"]
