name: Build images

on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  pull_request:

env:
  CI: 1
  REGISTRY: ghcr.io

concurrency:
  group: image-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    name: Build and publish images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode:
          - release
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install docker-buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup container metadata
        id: meta-anchor
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/anchor
          tags: |
            0.30.0
          flavor: |
            latest=auto
          bake-target: anchor

      - name: Setup container metadata
        id: meta-btc-rpc-explorer
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/btc-rpc-explorer
          tags: |
            3.4
          flavor: |
            latest=auto
          bake-target: btc-rpc-explorer

      - name: Setup container metadata
        id: meta-electrs
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/electrs
          tags: |
            0.10
          flavor: |
            latest=auto
          bake-target: electrs

      - name: Setup container metadata
        id: meta-sccache
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/sccache
          tags: |
            0.8.0
          flavor: |
            latest=auto
          bake-target: sccache

      - name: Merge container metadata
        run: |
          jq 'reduce inputs as $in (.; . * $in)' \
            ${{ steps.meta-anchor.outputs.bake-file }} \
            ${{ steps.meta-btc-rpc-explorer.outputs.bake-file }} \
            ${{ steps.meta-electrs.outputs.bake-file }} \
            ${{ steps.meta-sccache.outputs.bake-file }} > /tmp/bake-metadata.json

      - name: Build container image
        uses: docker/bake-action@v4
        with:
          pull: true
          push: true
          files: |
            ./docker-bake.hcl
            /tmp/bake-metadata.json

      - name: Clean container metadata
        run: |
          rm /tmp/bake-metadata.json
